name: zhihu-archiver
version: 0.1.0.0
github: "aplqo/zhihu-archiver"
license: GPL-3.0-or-later
author: "aplqo"
maintainer: "aplqo@outlook.com"
copyright: "2022 aplqo"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aplqo/zhihu-archiver#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeApplications
  dependencies:
    - aeson >= 2.0 && < 3
    - aeson-pretty >= 0.8 && < 1
    - time >= 1.9 && < 2
    - req >= 3 && < 4
    - http-client >= 0.7 && < 1
    - http-types >= 0.12 && < 1
    - text >= 1.2 && < 2
    - bytestring >= 0.10 && < 1
    - modern-uri >= 0.3 && < 1
    - template-haskell >= 2 && < 3
    - process >= 1.6 && < 2
    - cryptonite >=0.20 && < 1
    - case-insensitive >= 1.2 && < 2
    - unordered-containers >= 0.2 && < 1
    - vector >= 0.12 && < 1
    - hashable
    - memory
    - mtl
    - tagsoup
    - exceptions
    - containers
    - mime-types
    - filepath
    - directory
    - unix
    - pandoc
    - pandoc-types
    - data-default
  other-modules:
    - ZhArchiver.Image.TH
    - ZhArchiver.Raw.Parser.TH
    - ZhArchiver.Raw.Parser.Util

executables:
  zhihu-dl:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zhihu-archiver

tests:
  zhihu-archiver-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zhihu-archiver
